package com.libmailcore;

import java.util.List;
import java.util.Date;

public class MessageHeader extends NativeObject {
    
    public MessageHeader() {
        setupNative();
    }
    
    public MessageHeader(byte[] headersData) {
        setupNative();
        importHeadersData(headersData);
    }
    
    public native String messageID();
    public native void setMessageID(String messageID);
    
    public native boolean isMessageIDAutoGenerated();
    
    public native List<String> references();
    public native void setReferences(List<String> references);
    
    public native List<String> inReplyTo();
    public native void setInReplyTo(List<String> inReplyTo);
    
    public native Date date();
    public native void setDate(Date date);
    
    public native Date receivedDate();
    public native void setReceivedDate(Date date);
    
    public native Address sender();
    public native void setSender(Address sender);

    public native Address from();
    public native void setFrom(Address from);
    
    public native List<Address> to();
    public native void setTo(List<Address> to);

    public native List<Address> cc();
    public native void setCc(List<Address> cc);

    public native List<Address> bcc();
    public native void setBcc(List<Address> bcc);

    public native List<Address> replyTo();
    public native void setReplyTo(List<Address> replyTo);

    public native String subject();
    public native void setSubject(String subject);

    public native String userAgent();
    public native void setUserAgent(String userAgent);
    
    public native void setExtraHeader(String name, String value);
    public native void removeExtraHeader(String name);
    public native String extraHeaderValueForName(String name);
    public native List<String> allExtraHeadersNames();
    
    public native String extractedSubject();
    public native String partialExtractedSubject();
    
    public native void importHeadersData(byte[] data);
    
    public native MessageHeader replyHeader(boolean replyAll, List<Address> excludedRecipients);
    public native MessageHeader forwardHeader();
    
    private native void setupNative();
}
