#import "MCOActiveSyncPrivate.h"

#define nativeType mailcore::ActiveSyncMove
MCO_DEFINE_ACTIVE_SYNC_WRAPPER(MCOActiveSyncMove, mailcore::ActiveSyncMove)
MCO_OBJC_SYNTHESIZE_STRING(setSourceMessageID, sourceMessageID)
MCO_OBJC_SYNTHESIZE_STRING(setSourceFolderID, sourceFolderID)
MCO_OBJC_SYNTHESIZE_STRING(setDestinationFolderID, destinationFolderID)
MCO_END_ACTIVE_SYNC_WRAPPER
#undef nativeType
