//
//  MCValuePrivate.h
//  mailcore2
//
//  Created by DINH Viêt Hoà on 3/21/13.
//  Copyright (c) 2013 MailCore. All rights reserved.
//

#ifndef __MAILCORE_MCVALUEPRIVATE_H_

#define __MAILCORE_MCVALUEPRIVATE_H_

enum {
    VALUE_TYPE_NONE,
    VALUE_TYPE_BOOL_VALUE,
    VALUE_TYPE_CHAR_VALUE,
    VALUE_TYPE_UNSIGNED_CHAR_VALUE,
    VALUE_TYPE_SHORT_VALUE,
    VALUE_TYPE_UNSIGNED_SHORT_VALUE,
    VALUE_TYPE_INT_VALUE,
    VALUE_TYPE_UNSIGNED_INT_VALUE,
    VALUE_TYPE_LONG_VALUE,
    VALUE_TYPE_UNSIGNED_LONG_VALUE,
    VALUE_TYPE_LONG_LONG_VALUE,
    VALUE_TYPE_UNSIGNED_LONG_LONG_VALUE,
    VALUE_TYPE_FLOAT_VALUE,
    VALUE_TYPE_DOUBLE_VALUE,
    VALUE_TYPE_POINTER_VALUE,
    VALUE_TYPE_DATA_VALUE,
};

#endif
