/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPMessageRenderingOperation */

#ifndef _Included_com_libmailcore_IMAPMessageRenderingOperation
#define _Included_com_libmailcore_IMAPMessageRenderingOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_IMAPMessageRenderingOperation
 * Method:    result
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_IMAPMessageRenderingOperation_result
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
