/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPListNewsgroupsOperation */

#ifndef _Included_com_libmailcore_NNTPListNewsgroupsOperation
#define _Included_com_libmailcore_NNTPListNewsgroupsOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_NNTPListNewsgroupsOperation
 * Method:    groups
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NNTPListNewsgroupsOperation_groups
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
