/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_SMTPOperation */

#ifndef _Included_com_libmailcore_SMTPOperation
#define _Included_com_libmailcore_SMTPOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_SMTPOperation
 * Method:    errorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libmailcore_SMTPOperation_errorCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
