/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NativeObject */

#ifndef _Included_com_libmailcore_NativeObject
#define _Included_com_libmailcore_NativeObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_NativeObject
 * Method:    initWithNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NativeObject_initWithNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libmailcore_NativeObject
 * Method:    unsetupNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_NativeObject_unsetupNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NativeObject
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libmailcore_NativeObject_toString
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NativeObject
 * Method:    clone
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NativeObject_clone
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NativeObject
 * Method:    serializable
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NativeObject_serializable
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_NativeObject
 * Method:    objectWithSerializable
 * Signature: (Ljava/util/Map;)Lcom/libmailcore/NativeObject;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_NativeObject_objectWithSerializable
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
