/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPFetchMessagesOperation */

#ifndef _Included_com_libmailcore_IMAPFetchMessagesOperation
#define _Included_com_libmailcore_IMAPFetchMessagesOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_IMAPFetchMessagesOperation
 * Method:    messages
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFetchMessagesOperation_messages
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchMessagesOperation
 * Method:    vanishedMessages
 * Signature: ()Lcom/libmailcore/IndexSet;
 */
JNIEXPORT jobject JNICALL Java_com_libmailcore_IMAPFetchMessagesOperation_vanishedMessages
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchMessagesOperation
 * Method:    finalizeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchMessagesOperation_finalizeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_libmailcore_IMAPFetchMessagesOperation
 * Method:    setupNativeOperationProgressListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libmailcore_IMAPFetchMessagesOperation_setupNativeOperationProgressListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
