/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_NNTPFetchArticleOperation */

#ifndef _Included_com_libmailcore_NNTPFetchArticleOperation
#define _Included_com_libmailcore_NNTPFetchArticleOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libmailcore_NNTPFetchArticleOperation
 * Method:    data
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libmailcore_NNTPFetchArticleOperation_data
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
